name: basd-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - dask[complete]
  - esmpy
  - joblib
  - matplotlib!=3.6.1,>=3.1
  - netCDF4
  - numpy>=1.23
  - pandas
  - plotly
  - PyYAML>=5.4.1
  - rasterio
  - rioxarray
  - scipy
  - seaborn
  - xarray
  - xesmf