name: basd-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - setuptools
  - pytest
  - dask[complete]
  - esmpy
  - joblib
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - plotly
  - PyYAML
  - rasterio
  - rioxarray
  - scipy
  - seaborn
  - xarray
  - xesmf