name: build

on: [push, pull_request]

jobs:
  build:

      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          include:
            - os: ubuntu-latest
              label: linux-64
              prefix: /usr/share/miniconda3/envs/basd-env

      steps:

        - uses: actions/checkout@v2

        - name: Set up Mambaforge
          uses: conda-incubator/setup-miniconda@v2
          with:
            mamba-version: "*"
            channels: conda-forge,defaults
            auto-activate-base: false
            activate-environment: basd_env
            environment-file: environment.yml

        - name: Check modules
          run: mamba env export

        #- name: Install basd
        #  run: |
        #    # python -m pip install --upgrade pip
        #    # pip install -e .

        - name: Run tests
          shell: bash -l {0}
          run: pytest --cov=./basd/tests --cov-report=xml

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:        
            flags: unittests
            env_vars: OS,PYTHON
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true