name: build

on: [push, pull_request]

env:
  CACHE_NUMBER: 0

jobs:
  build:

      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          include:
            - os: ubuntu-latest
              label: linux-64
              prefix: /usr/share/miniconda3/envs/basd-env

      steps:

        - uses: actions/checkout@v2

        - name: Set up Mambaforge
          uses: conda-incubator/setup-miniconda@v2
          with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: basd-env
            use-mamba: true

        - name: Set cache data
          run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

        - uses: actions/cache@v2
          with:
            path: ${{ matrix.prefix }}
            key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
          id: cache

        - name: Update environment
          run: |
            mamba env update -n basd-env -f environment.yml
            python -m pip install --upgrade pip
            pip install -e .
          if: steps.cache.outputs.cache-hit != 'true'

        - name: Run tests
          shell: bash -l {0}
          run: pytest --cov=./ --cov-report=xml

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:        
            flags: unittests
            env_vars: OS,PYTHON
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true